language: node_js
node_js:
- '8'
- '6'
git:
  depth: 5
cache: yarn
script:
- if [[ "$TRAVIS_JOB_NUMBER" == *.1 ]]; then npm run lint && npm run check && npm
  run cover:lcov && cat ./coverage/lcov.info | coveralls; else npm run testonly; fi
jobs:
  include:
  - stage: Deploy
    script: echo "Deploying..."
    node_js: '8'
    deploy:
    - provider: script
      script: npm run gitpublish
      skip_cleanup: true
      on:
        branch: master
    - provider: npm
      skip_cleanup: true
      email: tobias@klemmer.info
      api_key:
        secure: YQMZPYcn5nVufZr7hIQDpRUJWDdmGk40eLZx/7Ovz2QCWwROm8eNTkw6mvAjU9EwuWuNvCwhbzcL99iOmRY8uSgaeyFiSdpvGKCzeXYShvK/cWE2MWDKP3ixQwrsPrjI3DDv6ViJDaVqfEisDSYYlc5TXFnqtN3QmqNbmR66+md7x/YxcAz4RezsmNusI4jELomu+vYmINF65PMWxeevp7UkbI5BnqzwKUw6nKXX8/+cStO7+T8Mha2St3Vk4Rc4zmPf70DxLILOfoxQGnXym1mSjRF4FHTHrlYc0XvxjegTWmkravKyTBVlb2ET5UyLD23MnHdsYVitBkG34JNjk+9DMjWVoGQRkwXVVlyzgHse/b/niglcCzawhG5aupc7Zktt4siGlRK7EAHoeuMIqwB6e5kSYCpaC75Hm+IhAOwOUP14PWyD2DA3tS30/2BFstWCidQtJPMhmtkjM+XtoO94a4S7KVeyIns93OkhsIGuOw/Cbg/1CkzKRlGJxvnYIpEgewH9ihKYBAMQfHb/1LASsaiB7PD7JphBgOEyNw+OGki4ZIERRUhJpJmrFgbtjbIsw5fHT7tDLuTNZdqSFnlqMrfn5K8UZPNpL1cTcdeO6il4OjM3xI6DC/WLs7pT+KXB1PQXve/4pcxbq29uRK+y+DUxongPTz9B9sQL9S4=
      on:
        tags: true
        branch: master
